[build]
  functions = "node_modules/cmless/server/"
  publish = "dist/"
  command = "npm run build"

[dev]
  framework = "#custom"
  command = "cmless --port 8080"
  targetPort = 8080
  port = 3000
  publish = "dist"
  autoLaunch = false
