[Settings]
  ID = "vdsabev"

[build]
  publish = "build"
  command = "npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Service Worker kill switch
# https://w3c.github.io/webappsec-clear-site-data/#example-killswitch
# [[headers]]
#   for = "/*"
#   [headers.values]
#     Clear-Site-Data = "*"
